"""Hierarchical Prompt Generator (L1 - L4) for MFVLR / GenFace reproduction dataset.

Generates independent L1 to L4 prompts according to GenFace and MFVLR specifications:
- L1 (Authenticity): "A photo of a real face" / "A photo of a fake face"
- L2 (Manipulation Category): "A photo of a real face" / "A photo of an entire synthesized face" /
                              "A photo of an identity swapped face" / "A photo of an attribute manipulated face"
- L3 (Generative Architecture): "A photo of a real face" / "A photo generated by the diffusion-based model" /
                                "A photo generated by the GAN-based model"
- L4 (Named Generator): "A photo of a real face" / "The source generative model of this photo is {generator}"

Rule: Do NOT concatenate L1-L4 into a single prompt string unless explicitly requested.
"""

import argparse
import logging
import os
import sys
from pathlib import Path
from typing import Any, Dict, Optional, Union

import yaml

if hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if hasattr(sys.stderr, "reconfigure"):
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

logging.basicConfig(
    level=logging.INFO,
    format="[%(asctime)s] [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("PromptGenerator")

# Standard prompt templates specified by GenFace and MFVLR
L1_REAL = "A photo of a real face"
L1_FAKE = "A photo of a fake face"

L2_MAP = {
    "REAL": "A photo of a real face",
    "EFS": "A photo of an entire synthesized face",
    "FS": "A photo of an identity swapped face",
    "AM": "A photo of an attribute manipulated face",
}

L3_MAP = {
    "REAL": "A photo of a real face",
    "DIFFUSION": "A photo generated by the diffusion-based model",
    "GAN": "A photo generated by the GAN-based model",
}


def load_generators_config(config_path: Union[str, Path] = "configs/generators.yaml") -> Dict[str, Dict[str, Any]]:
    """Load generator specifications from YAML configuration file."""
    path = Path(config_path)
    if not path.exists():
        logger.warning(f"Generators config not found at {path}. Using empty fallback.")
        return {}
    with open(path, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f)
    return data or {}


class PromptGenerator:
    """Class to generate hierarchical L1-L4 prompts with generator config resolution."""

    def __init__(self, config_path: Optional[Union[str, Path]] = "configs/generators.yaml"):
        self.config_path = config_path
        self.generators_cfg = load_generators_config(config_path) if config_path else {}

    def generate(
        self,
        label: int,
        forgery_type: Optional[str] = None,
        architecture: Optional[str] = None,
        generator: Optional[str] = None,
    ) -> Dict[str, str]:
        """Generate independent L1-L4 prompts for a sample.

        Args:
            label: 0 for Real, 1 for Fake.
            forgery_type: One of 'REAL', 'EFS', 'AM', 'FS' (optional if generator in config).
            architecture: One of 'REAL', 'Diffusion', 'GAN' (optional if generator in config).
            generator: Generator name (e.g. 'DDPM', 'DiffFace', 'StyleGAN3', 'Real').

        Returns:
            Dictionary containing 'L1', 'L2', 'L3', and 'L4'.
        """
        if label not in (0, 1):
            raise ValueError(f"Invalid label: {label}. Must be 0 or 1.")

        # Resolve from config if generator is provided
        if generator and generator in self.generators_cfg:
            gen_info = self.generators_cfg[generator]
            if forgery_type is None:
                forgery_type = gen_info.get("forgery_type")
            if architecture is None:
                architecture = gen_info.get("architecture")

        if label == 0:
            real_text = L1_REAL
            return {
                "L1": real_text,
                "L2": real_text,
                "L3": real_text,
                "L4": real_text,
            }

        # Fake image
        l1 = L1_FAKE

        # L2: Forgery type
        f_type = (forgery_type or "EFS").upper()
        if f_type not in L2_MAP:
            raise ValueError(f"Unknown forgery_type: '{forgery_type}'. Expected one of {list(L2_MAP.keys())}")
        l2 = L2_MAP[f_type]

        # L3: Architecture family
        arch = (architecture or "Diffusion").upper()
        if arch not in L3_MAP:
            raise ValueError(f"Unknown architecture: '{architecture}'. Expected one of {list(L3_MAP.keys())}")
        l3 = L3_MAP[arch]

        # L4: Named generator
        gen_name = generator or "unknown"
        l4 = f"The source generative model of this photo is {gen_name}"

        return {
            "L1": l1,
            "L2": l2,
            "L3": l3,
            "L4": l4,
        }

    def generate_from_generator_name(self, generator: str) -> Dict[str, str]:
        """Convenience method to generate prompts resolved solely from generator name in config."""
        if generator not in self.generators_cfg:
            # Case-insensitive search
            matched = None
            for k in self.generators_cfg:
                if k.lower() == generator.lower():
                    matched = k
                    break
            if not matched:
                raise ValueError(f"Generator '{generator}' not found in configuration.")
            generator = matched

        gen_info = self.generators_cfg[generator]
        forgery_type = gen_info.get("forgery_type", "EFS")
        architecture = gen_info.get("architecture", "Diffusion")
        label = 0 if forgery_type == "REAL" else 1

        return self.generate(
            label=label,
            forgery_type=forgery_type,
            architecture=architecture,
            generator=generator,
        )


def generate_prompts(
    label: int,
    forgery_type: Optional[str] = None,
    architecture: Optional[str] = None,
    generator: Optional[str] = None,
    config_path: Optional[Union[str, Path]] = "configs/generators.yaml",
) -> Dict[str, str]:
    """Convenience functional interface matching the README API."""
    pg = PromptGenerator(config_path=config_path)
    return pg.generate(
        label=label,
        forgery_type=forgery_type,
        architecture=architecture,
        generator=generator,
    )


def main():
    parser = argparse.ArgumentParser(description="Generate hierarchical prompts (L1-L4) for MFVLR dataset.")
    parser.add_argument("--config", type=str, default="configs/generators.yaml", help="Path to generators.yaml")
    parser.add_argument("--label", type=int, default=1, choices=[0, 1], help="0 for Real, 1 for Fake")
    parser.add_argument("--forgery-type", type=str, default=None, choices=["REAL", "EFS", "AM", "FS"], help="Forgery category")
    parser.add_argument("--architecture", type=str, default=None, choices=["REAL", "Diffusion", "GAN"], help="Generative family")
    parser.add_argument("--generator", type=str, default="DiffFace", help="Named generator (e.g. DDPM, DiffFace, StyleGAN3)")
    parser.add_argument("--dry-run", action="store_true", help="Perform dry run and print sample prompts for all configured generators")
    args = parser.parse_args()

    pg = PromptGenerator(config_path=args.config)

    if args.dry_run:
        logger.info("[Dry Run] Generating sample prompts for all generators in configuration:")
        # 1. Real sample
        real_p = pg.generate(label=0, generator="Real")
        logger.info(f"REAL: {real_p}")

        # 2. All configured fake generators
        for gen_name, gen_info in pg.generators_cfg.items():
            if gen_name.lower() == "real":
                continue
            p = pg.generate(
                label=1,
                forgery_type=gen_info.get("forgery_type"),
                architecture=gen_info.get("architecture"),
                generator=gen_name,
            )
            logger.info(f"FAKE [{gen_name}]: {p}")
        logger.info("[Dry Run] Prompt generator validation passed.")
        return

    prompts = pg.generate(
        label=args.label,
        forgery_type=args.forgery_type,
        architecture=args.architecture,
        generator=args.generator,
    )
    logger.info("Generated prompts:")
    for k, v in prompts.items():
        print(f"  {k}: {v}")


if __name__ == "__main__":
    main()
