"""Test FineGrainedTextGenerator for hierarchical prompts (L1 to L4)."""

import pytest
from datasets.prompt_generator import FineGrainedTextGenerator


def test_real_prompts():
    """Verify real face generates 'A photo of a real face' across all levels."""
    ftg = FineGrainedTextGenerator()
    prompts = ftg.generate_prompts(is_fake=False)

    assert prompts["L1"] == "A photo of a real face"
    assert prompts["L2"] == "A photo of a real face"
    assert prompts["L3"] == "A photo of a real face"
    assert prompts["L4"] == "A photo of a real face"


def test_fake_ddpm_prompts():
    """Verify DDPM prompts match Section III-D and Fig. 6."""
    ftg = FineGrainedTextGenerator()
    prompts = ftg.generate_prompts(is_fake=True, generator="DDPM")

    assert prompts["L1"] == "A photo of a fake face"
    assert prompts["L2"] == "A photo of an entire synthesized face"
    assert prompts["L3"] == "A photo generated by the diffusion-based model"
    assert prompts["L4"] == "The source generative model of this photo is DDPM"


def test_fake_stylegan3_prompts():
    """Verify StyleGAN3 prompts match Section III-D and Fig. 6."""
    ftg = FineGrainedTextGenerator()
    prompts = ftg.generate_prompts(is_fake=True, generator="StyleGAN3")

    assert prompts["L1"] == "A photo of a fake face"
    assert prompts["L2"] == "A photo of an entire synthesized face"
    assert prompts["L3"] == "A photo generated by the GAN-based model"
    assert prompts["L4"] == "The source generative model of this photo is StyleGAN3"


def test_fake_fslsd_prompts():
    """Verify FSLSD prompts (face swapping)."""
    ftg = FineGrainedTextGenerator()
    prompts = ftg.generate_prompts(is_fake=True, generator="FSLSD")

    assert prompts["L1"] == "A photo of a fake face"
    assert prompts["L2"] == "A photo of an identity swapped face"
    assert prompts["L3"] == "A photo generated by the GAN-based model"
    assert prompts["L4"] == "The source generative model of this photo is FSLSD"


def test_fake_diffae_prompts():
    """Verify Diffae prompts (attribute manipulation)."""
    ftg = FineGrainedTextGenerator()
    prompts = ftg.generate_prompts(is_fake=True, generator="Diffae")

    assert prompts["L1"] == "A photo of a fake face"
    assert prompts["L2"] == "A photo of an attribute manipulated face"
    assert prompts["L3"] == "A photo generated by the diffusion-based model"
    assert prompts["L4"] == "The source generative model of this photo is Diffae"
