import os
import sys
import time
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path

# Add project root and diffae to sys.path
sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.abspath("external/diffae"))

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    compute_difference_mask,
    save_mask_lossless,
)

GENERATOR = "DiffAE"
FORGERY_TYPE = "AM"
ARCHITECTURE = "Diffusion"
CATEGORY = "AM"
REPO = "https://github.com/konpatp/diffae"
COMMIT = "00c57d3f626f28bf9ed8aff58d90baab25de3af4"
CKPT_AUTOENC = "checkpoints/AM/DiffAE/ffhq256_autoenc/last.ckpt"
SHA_AUTOENC = "9bd2ba9e4c22afde8f18958026a4e8e625ef67d2c3ee76bb3aa72f3e67d3b9ca"
CKPT_CLS = "checkpoints/AM/DiffAE/ffhq256_autoenc_cls/last.ckpt"
SHA_CLS = "a83381098ec856ee07acfc0fed2d99f5d039c532b48ba43aef800eaca3731134"
ORIGINAL_DATASET = "FFHQ"
NATIVE_RESOLUTION = "256x256"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an attribute manipulated face"
L3 = "A photo generated by the diffusion-based model"
L4 = "The source generative model of this photo is DiffAE"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    src_dir = PREPROD_ROOT / "source" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load DiffAE models
    print("Loading official DiffAE LitModel...", flush=True)
    from templates import ffhq256_autoenc
    from experiment import LitModel

    conf = ffhq256_autoenc()
    model = LitModel(conf)
    state = torch.load(CKPT_AUTOENC, map_location="cpu", weights_only=False)
    model.load_state_dict(state["state_dict"])
    model.eval().to(device)

    # Load classifier normal vector for smiling attribute (CelebA attr 31)
    print("Loading classifier normal vector for smiling attribute (attr 31)...", flush=True)
    cls_state = torch.load(CKPT_CLS, map_location="cpu", weights_only=False)
    w = cls_state["state_dict"]["classifier.weight"][31].detach().to(device)
    w = w / torch.norm(w)
    print("DiffAE model and classifier vector ready on CUDA!", flush=True)

    # Available real pristine source faces (15 faces)
    real_src_paths = [Path(f"MFVLR_Dataset/images/real/{i:06d}.png") for i in range(15)]
    for p in real_src_paths:
        if not p.exists():
            raise FileNotFoundError(f"Real source face not found: {p}")

    # Pre-invert and cache 15 source faces (DDIM inversion T=250)
    print("Pre-inverting 15 real pristine source faces (DDIM inversion T=250)...", flush=True)
    cached_src = {}
    for s_idx in range(15):
        src_raw = Image.open(real_src_paths[s_idx]).convert("RGB").resize((256, 256))
        x_src = torch.from_numpy(np.array(src_raw)).permute(2, 0, 1).unsqueeze(0).float() / 127.5 - 1.0
        x_src = x_src.to(device)
        with torch.no_grad():
            z_sem = model.encode(x_src)
            x_T = model.encode_stochastic(x_src, z_sem, T=250)
        cached_src[s_idx] = (src_raw, z_sem, x_T)
        print(f"Source face {s_idx:02d}/15 inverted and cached.", flush=True)
    print("All 15 source faces cached successfully!", flush=True)

    # Build 500 deterministic combination pairs: (src_idx, alpha)
    # Vary alpha across discrete steps [0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, ...]
    alphas = [0.5 + 0.1 * k for k in range(35)]
    combos = []
    for s_idx in range(15):
        for a in alphas:
            combos.append((s_idx, a))
            if len(combos) >= NUM_SAMPLES:
                break
        if len(combos) >= NUM_SAMPLES:
            break

    print(f"Prepared {len(combos)} (source_idx, alpha) manipulation tasks.", flush=True)

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    for idx, (s_idx, alpha_val) in enumerate(combos):
        sample_id = f"diffae_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        src_path = src_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_src_path = str(src_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, src_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(src_path), Image.open(msk_path), Image.open(img_path)])
                continue

        src_raw, z_sem, x_T = cached_src[s_idx]

        t0 = time.time()
        with torch.no_grad():
            # 1. Latent shift
            z_manip = z_sem + alpha_val * np.sqrt(512) * w.unsqueeze(0)

            # 2. Render with shifted semantic code
            fake_tensor = model.render(x_T, z_manip, T=100)
            fake_tensor = torch.clamp(fake_tensor, 0.0, 1.0)
            fake_np = (fake_tensor[0].permute(1, 2, 0).cpu().numpy() * 255.0).astype(np.uint8)

        # Source face PIL (224x224)
        src_pil = src_raw.resize((224, 224), Image.Resampling.LANCZOS)
        src_pil.save(src_path, format="PNG")

        # Fake face PIL (224x224)
        fake_pil = Image.fromarray(fake_np).resize((224, 224), Image.Resampling.LANCZOS)
        fake_pil.save(img_path, format="PNG")

        # MFVLR strict mask protocol: abs(fake - source) -> ITU-R BT.601 -> /255.0 -> > 0.1 -> {0, 255}
        mask_arr = compute_difference_mask(fake_pil, src_pil, target_size=(224, 224), threshold=0.1)
        save_mask_lossless(mask_arr, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": rel_src_path,
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": "ffhq256_autoenc/last.ckpt",
            "checkpoint_sha256": SHA_AUTOENC,
            "seed": str(idx),
            "source_id": f"{s_idx:06d}.png",
            "target_id": "",
            "generation_config": f"attribute=smiling,alpha={alpha_val:.2f},inv_T=250,render_T=100",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": f"Official DiffAE smiling attribute manipulation (alpha={alpha_val:.2f}) pre-production sample",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([src_pil, Image.fromarray(mask_arr), fake_pil])

        if (idx + 1) % 10 == 0 or idx == len(combos) - 1:
            print(f"Progress: {idx + 1}/{len(combos)} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "diffae_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
