import os
import sys
import gc
import time
import psutil
import torch
import torch.nn.functional as F
import numpy as np
from PIL import Image
from pathlib import Path
from omegaconf import OmegaConf

# Keep project root in sys.path
PROJECT_ROOT = os.path.abspath(".")
sys.path.insert(0, PROJECT_ROOT)

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    save_mask_lossless,
)

GENERATOR = "CollDiff"
FORGERY_TYPE = "EFS"
ARCHITECTURE = "Diffusion"
CATEGORY = "EFS"
REPO = "https://github.com/ziqihuangg/Collaborative-Diffusion"
COMMIT = "a4a0d1f13bc83f2315cb885ef1095bb498c5984c"
CHECKPOINT = "external/colldiff/pretrained/256_codiff_mask_text.ckpt"
CHECKPOINT_SHA256 = "a1a280155bbf89ba7e2b1ea739d486259e81b6aa2828b6d193d56b005183dbd0"
CONFIG_PATH = "configs/256_codiff_mask_text.yaml"
ORIGINAL_DATASET = "CelebA-HQ"
NATIVE_RESOLUTION = "256x256"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an entire synthesized face"
L3 = "A photo generated by the diffusion-based model"
L4 = "The source generative model of this photo is CollDiff"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===", flush=True)
    init_workspace()

    colldiff_root = os.path.abspath("external/colldiff")
    sys.path.insert(0, colldiff_root)

    from ldm.util import instantiate_from_config
    from ldm.models.diffusion.ddim_confidence import DDIMConfidenceSampler

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}", flush=True)

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # CollDiff requires cwd in colldiff_root to load sub-configs properly
    old_cwd = os.getcwd()
    os.chdir(colldiff_root)

    try:
        print("Loading official CollDiff model from configs/256_codiff_mask_text.yaml...", flush=True)
        config = OmegaConf.load(CONFIG_PATH)
        model = instantiate_from_config(config["model"])
        print("Initializing weights from pretrained/256_codiff_mask_text.ckpt...", flush=True)
        model.init_from_ckpt("pretrained/256_codiff_mask_text.ckpt")
        model = model.to(device)
        model.eval()
        print("CollDiff model ready on CUDA!", flush=True)

        # Prepare condition inputs
        mask_path = "test_data/256_masks/29980.png"
        input_text = "This woman is in her forties."

        with open(mask_path, "rb") as f:
            img = Image.open(f)
            resized_img = img.resize((32, 32), Image.NEAREST)
            flattened_img = list(resized_img.getdata())
        flattened_img_tensor = torch.tensor(flattened_img)
        flattened_img_tensor_one_hot = F.one_hot(flattened_img_tensor, num_classes=19).transpose(0, 1)
        flattened_img_tensor_one_hot_transpose = torch.unsqueeze(flattened_img_tensor_one_hot, 0).to(device)

        condition = {
            "seg_mask": flattened_img_tensor_one_hot_transpose,
            "text": [input_text.lower()],
        }

        # Pre-create all-ones mask array (224x224)
        efs_mask = np.full((224, 224), 255, dtype=np.uint8)

        times = []
        contact_samples = []
        generated_count = 0
        skipped_count = 0

        if torch.cuda.is_available():
            torch.cuda.reset_peak_memory_stats()
        process = psutil.Process()

        for idx in range(NUM_SAMPLES):
            sample_id = f"colldiff_{idx:06d}"
            img_name = f"{sample_id}.png"
            img_path = img_dir / img_name
            msk_path = msk_dir / img_name

            rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
            rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

            # Check resumability
            if sample_id in existing_records:
                rec = existing_records[sample_id]
                if is_sample_valid_and_complete(sample_id, rec, [img_path, msk_path]):
                    skipped_count += 1
                    if len(contact_samples) < 10:
                        contact_samples.append([Image.open(img_path), Image.open(msk_path)])
                    continue

            seed = idx
            torch.manual_seed(seed)
            if torch.cuda.is_available():
                torch.cuda.manual_seed_all(seed)

            t0 = time.time()
            with torch.no_grad():
                with model.ema_scope("Plotting"):
                    condition_enc = model.get_learned_conditioning(condition)
                    ddim_sampler = DDIMConfidenceSampler(model=model, return_confidence_map=False)
                    z_0_batch, _ = ddim_sampler.sample(
                        S=50,
                        batch_size=1,
                        shape=(3, 64, 64),
                        conditioning=condition_enc,
                        verbose=False,
                        eta=1.0,
                        log_every_t=1,
                    )
                x_0_batch = model.decode_first_stage(z_0_batch)

            x_0 = x_0_batch[0].permute(1, 2, 0).cpu().numpy()
            x_0 = (x_0 + 1.0) * 127.5
            x_0 = np.clip(x_0, 0, 255).astype(np.uint8)

            # Resize to strict 224x224 MFVLR protocol
            img_pil = Image.fromarray(x_0).resize((224, 224), Image.Resampling.LANCZOS)
            img_pil.save(img_path, format="PNG")

            # Save EFS mask (all 255)
            save_mask_lossless(efs_mask, msk_path)

            dt = time.time() - t0
            times.append(dt)
            generated_count += 1

            img_sha = compute_sha256(img_path)

            record = {
                "sample_id": sample_id,
                "image_path": rel_img_path,
                "source_path": "",
                "target_path": "",
                "mask_path": rel_msk_path,
                "label": "1",
                "forgery_type": FORGERY_TYPE,
                "architecture": ARCHITECTURE,
                "generator": GENERATOR,
                "split": "UNASSIGNED",
                "L1": L1,
                "L2": L2,
                "L3": L3,
                "L4": L4,
                "original_dataset": ORIGINAL_DATASET,
                "generator_repo": REPO,
                "generator_commit": COMMIT,
                "checkpoint": CHECKPOINT,
                "checkpoint_sha256": CHECKPOINT_SHA256,
                "seed": str(seed),
                "source_id": "",
                "target_id": "",
                "generation_config": f"sampler=DDIMConfidenceSampler,S=50,eta=1.0,text='{input_text}'",
                "native_resolution": NATIVE_RESOLUTION,
                "sha256": img_sha,
                "notes": "Official CollDiff multi-modal synthesis pre-production sample (DDIM 50-step)",
            }
            append_metadata_record(csv_path, record)

            if len(contact_samples) < 10:
                contact_samples.append([img_pil, Image.fromarray(efs_mask)])

            if (idx + 1) % 50 == 0 or idx == NUM_SAMPLES - 1:
                print(f"Progress: {idx + 1}/{NUM_SAMPLES} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

        peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
        peak_ram = process.memory_info().rss / (1024 ** 2)
        avg_runtime = sum(times) / len(times) if times else 0

        print("\n" + "=" * 60, flush=True)
        print(f"{GENERATOR} COMPLETED:", flush=True)
        print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
        print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
        print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
        print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
        print("=" * 60, flush=True)

        # Save visual grid
        grid_path = PREPROD_ROOT / "visual_grids" / "colldiff_preprod_grid.png"
        create_contact_sheet(contact_samples, grid_path)
        print(f"Saved visual grid to {grid_path}", flush=True)

    finally:
        os.chdir(old_cwd)


if __name__ == "__main__":
    main()
