import os
import sys
import time
import ctypes
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, os.path.abspath("."))

def get_short_path(path):
    buf = ctypes.create_unicode_buffer(500)
    ctypes.windll.kernel32.GetShortPathNameW(os.path.abspath(path), buf, 500)
    return buf.value

msvc_bin = r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64"
cuda_home = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library"
scripts_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Scripts"
nvcc_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library\bin"

os.environ["CUDA_HOME"] = cuda_home
os.environ["CUDA_PATH"] = cuda_home
os.environ["PATH"] = f"{msvc_bin};{nvcc_bin};{scripts_bin};" + os.environ["PATH"]

import distutils
import distutils._msvccompiler
import pathlib
pathlib.PosixPath = pathlib.WindowsPath

import torch.utils.cpp_extension

orig_load = torch.utils.cpp_extension.load
def patched_load(name, sources, *args, **kwargs):
    cuda_flags = kwargs.get("extra_cuda_cflags", [])
    for f in ["-allow-unsupported-compiler", "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH"]:
        if f not in cuda_flags:
            cuda_flags.append(f)
    kwargs["extra_cuda_cflags"] = cuda_flags

    c_flags = kwargs.get("extra_cflags", [])
    if "/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH" not in c_flags:
        c_flags.append("/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH")
    kwargs["extra_cflags"] = c_flags

    short_sources = [os.path.join(get_short_path(os.path.dirname(s)), os.path.basename(s)) for s in sources]
    return orig_load(name, short_sources, *args, **kwargs)

torch.utils.cpp_extension.load = patched_load

short_iafaces = get_short_path("external/IA-FaceS/iafaces-eval")
sys.path.insert(0, short_iafaces)

from importlib import import_module
import albumentations as A
from albumentations.pytorch import ToTensorV2

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    compute_difference_mask,
    save_mask_lossless,
)

GENERATOR = "IAFaces"
FORGERY_TYPE = "AM"
ARCHITECTURE = "GAN"
CATEGORY = "AM"
REPO = "https://github.com/CMACH508/IA-FaceS.git"
COMMIT = "50e18fc091f03f5ce6bbd377b7f58cb2e93b4dd6"
CHECKPOINT = "checkpoints/AM/IAFaces/iafaces-celebahq-256.pth"
CHECKPOINT_SHA256 = "b08552b6c1adcc372b665e005cf1a4fa3a50112ba747391060e268db41b6cab2"
ORIGINAL_DATASET = "CelebA-HQ"
NATIVE_RESOLUTION = "256x256"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an attribute manipulated face"
L3 = "A photo generated by the gan-based model"
L4 = "The source generative model of this photo is IAFaces"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Verify checkpoint
    ckpt_path = Path(CHECKPOINT)
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found at {ckpt_path}")
    curr_sha = compute_sha256(ckpt_path)
    if curr_sha != CHECKPOINT_SHA256:
        raise ValueError(f"Checkpoint SHA256 mismatch: {curr_sha} != {CHECKPOINT_SHA256}")
    print(f"Verified checkpoint SHA256: {curr_sha}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    src_dir = PREPROD_ROOT / "source" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load model
    print("Loading official IAFaces checkpoint and model...")
    ckpt = torch.load(ckpt_path, map_location="cpu")
    cfg_dict = ckpt["config"].config if hasattr(ckpt["config"], "config") else ckpt["config"]
    arch = cfg_dict["model_arch"]
    model_arch = import_module("model." + arch)

    netE = model_arch.Encoder(**cfg_dict["encoder"]["args"])
    netG = model_arch.Generator(**cfg_dict["generator"]["args"])
    netE.load_state_dict(ckpt["e_ema"])
    netG.load_state_dict(ckpt["g_ema"])
    netE.eval().to(device)
    netG.eval().to(device)
    print("IAFaces models ready on CUDA!")

    # Preprocessing transform
    transform = A.Compose([
        A.Resize(height=256, width=256),
        A.Normalize(mean=(0.5, 0.5, 0.5), std=(0.5, 0.5, 0.5)),
        ToTensorV2(),
    ])

    def preprocess_pil(img_pil):
        img_np = np.array(img_pil.convert("RGB"))
        return transform(image=img_np)["image"].unsqueeze(0).to(device)

    # Available real pristine source faces (15 faces)
    real_src_paths = [Path(f"MFVLR_Dataset/images/real/{i:06d}.png") for i in range(15)]
    for p in real_src_paths:
        if not p.exists():
            raise FileNotFoundError(f"Real source face not found: {p}")

    # Pre-cache encoded features for all 15 real faces
    print("Pre-encoding 15 real pristine faces with netE...")
    cached_feats = {}
    with torch.no_grad():
        for i, p in enumerate(real_src_paths):
            with Image.open(p) as img:
                img_t = preprocess_pil(img)
                face, nodes = netE(img_t)
                cached_feats[i] = (face, nodes)

    # Build 500 deterministic combination pairs: (src_idx, ref_idx, comp_indices, comp_name)
    components = [
        ([0, 1], "eyes"),
        ([3], "mouth"),
        ([2], "nose"),
    ]
    combos = []
    for s_idx in range(15):
        for r_idx in range(15):
            if s_idx == r_idx:
                continue
            for comp_idx, comp_name in components:
                combos.append((s_idx, r_idx, comp_idx, comp_name))

    print(f"Total available component transfer combinations: {len(combos)}")
    combos = combos[:NUM_SAMPLES]

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    for idx, (s_idx, r_idx, comp_idx, comp_name) in enumerate(combos):
        sample_id = f"iafaces_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        src_path = src_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_src_path = str(src_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, src_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(src_path), Image.open(msk_path), Image.open(img_path)])
                continue

        src_face, src_nodes = cached_feats[s_idx]
        ref_face, ref_nodes = cached_feats[r_idx]

        t0 = time.time()
        with torch.no_grad():
            manip_nodes = src_nodes.clone()
            manip_nodes[:, comp_idx, :] = ref_nodes[:, comp_idx, :]
            fake_tensor = netG(src_face, manip_nodes, randomize_noise=False)

            fake_np = ((fake_tensor[0].permute(1, 2, 0).cpu().numpy().clip(-1, 1) + 1.0) / 2.0 * 255).astype(np.uint8)

        # Source face PIL (224x224)
        src_raw = Image.open(real_src_paths[s_idx]).convert("RGB")
        src_pil = src_raw.resize((224, 224), Image.Resampling.LANCZOS)
        src_pil.save(src_path, format="PNG")

        # Fake face PIL (224x224)
        fake_pil = Image.fromarray(fake_np).resize((224, 224), Image.Resampling.LANCZOS)
        fake_pil.save(img_path, format="PNG")

        # MFVLR strict mask protocol: abs(fake - source) -> ITU-R BT.601 -> /255.0 -> > 0.1 -> {0, 255}
        mask_arr = compute_difference_mask(fake_pil, src_pil, target_size=(224, 224), threshold=0.1)
        save_mask_lossless(mask_arr, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": rel_src_path,
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": CHECKPOINT,
            "checkpoint_sha256": CHECKPOINT_SHA256,
            "seed": str(idx),
            "source_id": f"{s_idx:06d}.png",
            "target_id": f"{r_idx:06d}.png",
            "generation_config": f"component={comp_name},transfer_indices={comp_idx}",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": f"Official IAFaces component transfer ({comp_name}) pre-production sample",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([src_pil, Image.fromarray(mask_arr), fake_pil])

        if (idx + 1) % 50 == 0 or idx == len(combos) - 1:
            print(f"Progress: {idx + 1}/{len(combos)} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "iafaces_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
