import os
import sys
import time
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path
from diffusers import DDPMPipeline, DDIMScheduler

# Add project root to sys.path
sys.path.insert(0, os.path.abspath("."))

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    save_mask_lossless,
)

GENERATOR = "DDPM"
FORGERY_TYPE = "EFS"
ARCHITECTURE = "Diffusion"
CATEGORY = "EFS"
REPO = "google/ddpm-celebahq-256"
COMMIT = "cd5c944777ea2668051904ead6cc120739b86c4d"
CHECKPOINT = "google/ddpm-celebahq-256"
CHECKPOINT_SHA256 = "6b81d77cb077d018788417c88b4ddc89a7444c1dcae9e0350a4ec9ec51787c8d"
ORIGINAL_DATASET = "CelebA-HQ"
NATIVE_RESOLUTION = "256x256"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an entire synthesized face"
L3 = "A photo generated by the diffusion-based model"
L4 = "The source generative model of this photo is DDPM"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load official pipeline
    print(f"Loading official {GENERATOR} pipeline...")
    pipe = DDPMPipeline.from_pretrained(CHECKPOINT)
    pipe.scheduler = DDIMScheduler.from_config(pipe.scheduler.config)
    pipe.to(device)
    print("DDPM pipeline ready on CUDA!")

    # Pre-create all-ones mask array (224x224)
    efs_mask = np.full((224, 224), 255, dtype=np.uint8)

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    for idx in range(NUM_SAMPLES):
        sample_id = f"ddpm_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(img_path), Image.open(msk_path)])
                continue

        seed = idx
        generator = torch.Generator(device=device).manual_seed(seed)

        t0 = time.time()
        with torch.no_grad():
            output = pipe(batch_size=1, generator=generator, num_inference_steps=50)
            img_pil_raw = output.images[0]

        # Resize to strict 224x224 MFVLR protocol
        img_pil = img_pil_raw.resize((224, 224), Image.Resampling.LANCZOS)
        img_pil.save(img_path, format="PNG")

        # Save EFS mask (all 255)
        save_mask_lossless(efs_mask, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": "",
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": CHECKPOINT,
            "checkpoint_sha256": CHECKPOINT_SHA256,
            "seed": str(seed),
            "source_id": "",
            "target_id": "",
            "generation_config": "scheduler=DDIMScheduler,num_inference_steps=50",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": "Official DDPM synthesis pre-production sample (DDIM 50-step)",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([img_pil, Image.fromarray(efs_mask)])

        if (idx + 1) % 50 == 0 or idx == NUM_SAMPLES - 1:
            print(f"Progress: {idx + 1}/{NUM_SAMPLES} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "ddpm_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
