import os
import sys
import time
import ctypes
import pickle
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path

# Add project root and stylegan3 to sys.path
sys.path.insert(0, os.path.abspath("."))

def get_short_path(path):
    buf = ctypes.create_unicode_buffer(500)
    ctypes.windll.kernel32.GetShortPathNameW(os.path.abspath(path), buf, 500)
    return buf.value

msvc_bin = r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64"
cuda_home = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library"
scripts_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Scripts"
nvcc_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library\bin"

os.environ["CUDA_HOME"] = cuda_home
os.environ["CUDA_PATH"] = cuda_home
os.environ["SETUPTOOLS_USE_DISTUTILS"] = "stdlib"
os.environ["PATH"] = f"{msvc_bin};{nvcc_bin};{scripts_bin};" + os.environ["PATH"]

import distutils
import distutils._msvccompiler
import torch.utils.cpp_extension

orig_load = torch.utils.cpp_extension.load
def patched_load(name, sources, *args, **kwargs):
    cuda_flags = kwargs.get("extra_cuda_cflags", [])
    for f in ["-allow-unsupported-compiler", "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH"]:
        if f not in cuda_flags:
            cuda_flags.append(f)
    kwargs["extra_cuda_cflags"] = cuda_flags

    c_flags = kwargs.get("extra_cflags", [])
    if "/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH" not in c_flags:
        c_flags.append("/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH")
    kwargs["extra_cflags"] = c_flags

    short_sources = [os.path.join(get_short_path(os.path.dirname(s)), os.path.basename(s)) for s in sources]
    return orig_load(name, short_sources, *args, **kwargs)

torch.utils.cpp_extension.load = patched_load

short_sg3 = get_short_path("external/stylegan3")
sys.path.insert(0, short_sg3)

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    save_mask_lossless,
)

GENERATOR = "StyleGAN3"
FORGERY_TYPE = "EFS"
ARCHITECTURE = "GAN"
CATEGORY = "EFS"
REPO = "https://github.com/NVlabs/stylegan3"
COMMIT = "07d031548e24483733230a103c80081bf582531d"
CHECKPOINT = "checkpoints/EFS/StyleGAN3/stylegan3-r-ffhq-1024x1024.pkl"
CHECKPOINT_SHA256 = "ffe2233fa0d0329ad9f19b8bf8ea855d12210461c118ff52fbffde8d3a2b4519"
ORIGINAL_DATASET = "FFHQ"
NATIVE_RESOLUTION = "1024x1024"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an entire synthesized face"
L3 = "A photo generated by the gan-based model"
L4 = "The source generative model of this photo is StyleGAN3"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===", flush=True)
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}", flush=True)

    # Verify checkpoint
    ckpt_path = Path(CHECKPOINT)
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found at {ckpt_path}")
    curr_sha = compute_sha256(ckpt_path)
    if curr_sha != CHECKPOINT_SHA256:
        raise ValueError(f"Checkpoint SHA256 mismatch: {curr_sha} != {CHECKPOINT_SHA256}")
    print(f"Verified checkpoint SHA256: {curr_sha}", flush=True)

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load official model with compiled native CUDA ops
    print(f"Loading official {GENERATOR} model...", flush=True)
    import legacy
    with open(ckpt_path, "rb") as f:
        data = legacy.load_network_pkl(f)
        G = data["G_ema"].to(device).eval()
    print("StyleGAN3 loaded successfully with native CUDA ops!", flush=True)

    # Pre-create all-ones mask array (224x224)
    efs_mask = np.full((224, 224), 255, dtype=np.uint8)

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    for idx in range(NUM_SAMPLES):
        sample_id = f"stylegan3_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(img_path), Image.open(msk_path)])
                continue

        # Deterministic generation per seed
        seed = idx
        t0 = time.time()
        with torch.no_grad():
            torch.manual_seed(seed)
            z = torch.randn([1, G.z_dim], device=device)
            c = None  # unconditional
            img_tensor = G(z, c, truncation_psi=0.7, noise_mode="const")
            img_tensor = (img_tensor.permute(0, 2, 3, 1) * 127.5 + 128).clamp(0, 255).to(torch.uint8)
            img_np = img_tensor[0].cpu().numpy()

        # Resize to strict 224x224 MFVLR protocol
        img_pil = Image.fromarray(img_np, mode="RGB").resize((224, 224), Image.Resampling.LANCZOS)
        img_pil.save(img_path, format="PNG")

        # Save EFS mask (all 255)
        save_mask_lossless(efs_mask, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": "",
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": CHECKPOINT,
            "checkpoint_sha256": CHECKPOINT_SHA256,
            "seed": str(seed),
            "source_id": "",
            "target_id": "",
            "generation_config": "truncation_psi=0.7,noise_mode=const",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": "Official StyleGAN3 synthesis pre-production sample",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([img_pil, Image.fromarray(efs_mask)])

        if (idx + 1) % 50 == 0 or idx == NUM_SAMPLES - 1:
            print(f"Progress: {idx + 1}/{NUM_SAMPLES} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "stylegan3_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
