import os
import sys
import time
import argparse
import psutil
import torch
import torch.nn.functional as F
import numpy as np
from PIL import Image
from pathlib import Path

# Add project root and FaceSwapper to sys.path
sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.abspath("external/FaceSwapper"))

from core.model import Generator
from core.face_model import Backbone
from core.wing import FAN
from core import utils

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    compute_difference_mask,
    save_mask_lossless,
)

GENERATOR = "FaceSwapper"
FORGERY_TYPE = "FS"
ARCHITECTURE = "GAN"
CATEGORY = "FS"
REPO = "https://github.com/liqi-casia/FaceSwapper"
COMMIT = "69f53e5e493214736f33cf224c084f74d081e7d2"
CKPT_GENERATOR = "external/FaceSwapper/pretrained_checkpoints/faceswapper.ckpt"
CKPT_ARCFACE = "external/FaceSwapper/pretrained_checkpoints/model_ir_se50.pth"
CKPT_WING = "external/FaceSwapper/pretrained_checkpoints/wing.ckpt"

SHA_GENERATOR = "74d781083057091ab8e74b9e86ce2c84a5b66c72dd1f218290e0aeaa0d87b4ee"
ORIGINAL_DATASET = "FaceForensics++"
NATIVE_RESOLUTION = "256x256"

L1 = "A photo of a fake face"
L2 = "A photo of an identity swapped face"
L3 = "A photo generated by the gan-based model"
L4 = "The source generative model of this photo is FaceSwapper"


def load_image_tensor(img_path, device):
    img = Image.open(img_path).convert("RGB").resize((256, 256))
    img_np = np.array(img).astype(np.float32) / 127.5 - 1.0  # [-1, 1]
    tensor = torch.from_numpy(img_np).permute(2, 0, 1).unsqueeze(0).to(device)
    return img, tensor


def load_mask_tensor(mask_path, device):
    img = Image.open(mask_path).convert("L").resize((256, 256))
    img_np = np.array(img).astype(np.float32) / 255.0
    tensor = torch.from_numpy(img_np).unsqueeze(0).unsqueeze(0).to(device)
    return 1.0 - tensor


def load_parsing_tensor(parsing_path, device):
    img = Image.open(parsing_path).convert("L").resize((256, 256))
    img_np = np.array(img).astype(np.float32) / 255.0
    tensor = torch.from_numpy(img_np).unsqueeze(0).unsqueeze(0).to(device)
    return tensor


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    src_dir = PREPROD_ROOT / "source" / CATEGORY / GENERATOR
    tar_dir = PREPROD_ROOT / "target" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR

    img_dir.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)
    tar_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load FaceSwapper models
    print("Loading official FaceSwapper generator, ArcFace, and FAN...", flush=True)
    from munch import Munch
    from core.model import build_model
    from core.checkpoint import CheckpointIO

    fs_cfg = Munch(
        dataset="celeba",
        img_size=256,
        id_dim=512,
        cuda_device="0",
        mode="test",
        test_checkpoint_dir="external/FaceSwapper/pretrained_checkpoints/",
        test_checkpoint_name="faceswapper.ckpt",
        wing_path=CKPT_WING,
        face_model_path=CKPT_ARCFACE,
    )

    nets, nets_ema = build_model(fs_cfg)
    ckptio = CheckpointIO(fs_cfg.test_checkpoint_dir, **nets_ema)
    ckptio.load_test(fs_cfg.test_checkpoint_name)
    G = nets_ema.generator.eval().to(device)

    fan = FAN(fname_pretrained=CKPT_WING).to(device)
    fan.eval()

    print("FaceSwapper models loaded successfully!", flush=True)

    # Build pairs from available FF++ dataset frames
    ff_dir = Path("external/FaceSwapper/data/FF++_Dataset/ff++")
    lm_dir = Path("external/FaceSwapper/data/FF++_Dataset/ff++_lm_images")
    mask_dir = Path("external/FaceSwapper/data/FF++_Dataset/ff++_mask_images")
    pars_dir = Path("external/FaceSwapper/data/FF++_Dataset/ff++_parsing_images")

    all_frames = sorted([f.name for f in ff_dir.glob("*.png")])
    print(f"Available FF++ frames: {len(all_frames)}")

    # Form all cross-identity pairs + intra-identity temporal swaps
    pairs = []
    # 1. Cross-identity 003 -> 000 and 000 -> 003
    for s_name in all_frames:
        for t_name in all_frames:
            if s_name != t_name:
                pairs.append((s_name, t_name))

    print(f"Prepared {len(pairs)} unique (source_id, target_context) swap pairs.")
    num_samples = min(len(pairs), 500)
    pairs = pairs[:num_samples]

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    for idx, (src_name, tar_name) in enumerate(pairs):
        sample_id = f"faceswapper_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        src_path = src_dir / img_name
        tar_path = tar_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_src_path = str(src_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_tar_path = str(tar_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, src_path, tar_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(src_path), Image.open(tar_path), Image.open(img_path), Image.open(msk_path)])
                continue

        src_pil, src_t = load_image_tensor(ff_dir / src_name, device)
        tar_pil, tar_t = load_image_tensor(ff_dir / tar_name, device)

        _, src_lm = load_image_tensor(lm_dir / src_name, device)
        _, tar_lm = load_image_tensor(lm_dir / tar_name, device)

        src_mask = load_mask_tensor(mask_dir / src_name, device)
        tar_mask = load_mask_tensor(mask_dir / tar_name, device)
        tar_parsing = load_parsing_tensor(pars_dir / tar_name, device)

        src_mask_res = F.interpolate(src_mask, src_t.size(2), mode="bilinear", align_corners=True)
        tar_mask_res = F.interpolate(tar_mask, src_t.size(2), mode="bilinear", align_corners=True)

        t0 = time.time()
        with torch.no_grad():
            srcid_taratt, _, _, _, _, _ = G(src_t, tar_t, src_lm, tar_lm, src_mask_res, tar_mask_res)

            src_convex_hull = fan.get_convex_hull(src_t)
            tar_convex_hull = fan.get_convex_hull(tar_t)
            temp_src_forehead = src_convex_hull - src_mask_res
            temp_tar_forehead = tar_convex_hull - tar_mask_res

            one_tensor = torch.ones_like(temp_src_forehead)
            zero_tensor = torch.zeros_like(temp_src_forehead)
            src_forehead = torch.where(temp_src_forehead >= 1.0, one_tensor, temp_src_forehead)
            src_forehead = torch.where(src_forehead <= 0.0, zero_tensor, src_forehead)
            tar_forehead = torch.where(temp_tar_forehead >= 1.0, one_tensor, temp_tar_forehead)
            tar_forehead = torch.where(tar_forehead <= 0.0, zero_tensor, tar_forehead)

            tar_hair = utils.get_hair(tar_parsing)
            swapped = utils.postprocess(tar_t, srcid_taratt, tar_hair, src_forehead, tar_forehead)

            swapped_np = swapped[0].cpu().permute(1, 2, 0).numpy()
            swapped_np = np.clip((swapped_np + 1.0) / 2.0 * 255.0, 0, 255).astype(np.uint8)

        # Save source identity (224x224)
        src_224 = src_pil.resize((224, 224), Image.Resampling.LANCZOS)
        src_224.save(src_path, format="PNG")

        # Save target context (224x224)
        tar_224 = tar_pil.resize((224, 224), Image.Resampling.LANCZOS)
        tar_224.save(tar_path, format="PNG")

        # Save fake face (224x224)
        fake_224 = Image.fromarray(swapped_np).resize((224, 224), Image.Resampling.LANCZOS)
        fake_224.save(img_path, format="PNG")

        # MFVLR strict mask protocol: abs(fake - target_context) -> ITU-R BT.601 -> /255.0 -> > 0.1 -> {0, 255}
        mask_arr = compute_difference_mask(fake_224, tar_224, target_size=(224, 224), threshold=0.1)
        save_mask_lossless(mask_arr, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": rel_src_path,
            "target_path": rel_tar_path,
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": "faceswapper.ckpt",
            "checkpoint_sha256": SHA_GENERATOR,
            "seed": str(idx),
            "source_id": src_name,
            "target_id": tar_name,
            "generation_config": f"source={src_name},target={tar_name}",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": f"Official FaceSwapper face swap ({src_name} -> {tar_name}) pre-production sample",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([src_224, tar_224, fake_224, Image.fromarray(mask_arr)])

        if (idx + 1) % 50 == 0 or idx == num_samples - 1:
            print(f"Progress: {idx + 1}/{num_samples} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "faceswapper_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
