import os
import sys
import time
import ctypes
import argparse
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path

# Add project root to sys.path
sys.path.insert(0, os.path.abspath("."))

def get_short_path(path):
    buf = ctypes.create_unicode_buffer(500)
    ctypes.windll.kernel32.GetShortPathNameW(os.path.abspath(path), buf, 500)
    return buf.value

msvc_bin = r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64"
cuda_home = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library"
scripts_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Scripts"
nvcc_bin = r"C:\Users\NHA\miniconda3\envs\lattrans_env\Library\bin"

os.environ["CUDA_HOME"] = cuda_home
os.environ["CUDA_PATH"] = cuda_home
os.environ["PATH"] = f"{msvc_bin};{nvcc_bin};{scripts_bin};" + os.environ["PATH"]

import distutils
import distutils._msvccompiler
import pathlib
pathlib.PosixPath = pathlib.WindowsPath

import torch.utils.cpp_extension
from torchvision import transforms

orig_load = torch.utils.cpp_extension.load
def patched_load(name, sources, *args, **kwargs):
    cuda_flags = kwargs.get("extra_cuda_cflags", [])
    for f in ["-allow-unsupported-compiler", "-D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH"]:
        if f not in cuda_flags:
            cuda_flags.append(f)
    kwargs["extra_cuda_cflags"] = cuda_flags

    c_flags = kwargs.get("extra_cflags", [])
    if "/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH" not in c_flags:
        c_flags.append("/D_ALLOW_COMPILER_AND_STL_VERSION_MISMATCH")
    kwargs["extra_cflags"] = c_flags

    short_sources = [os.path.join(get_short_path(os.path.dirname(s)), os.path.basename(s)) for s in sources]
    return orig_load(name, short_sources, *args, **kwargs)

torch.utils.cpp_extension.load = patched_load

short_lattrans = get_short_path("external/latent-transformer")
sys.path.insert(0, short_lattrans)
sys.path.insert(0, os.path.join(short_lattrans, "pixel2style2pixel"))

from pixel2style2pixel.models.psp import pSp
from nets import F_mapping

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    compute_difference_mask,
    save_mask_lossless,
)

GENERATOR = "LatTrans"
FORGERY_TYPE = "AM"
ARCHITECTURE = "GAN"
CATEGORY = "AM"
REPO = "https://github.com/InterDigitalInc/latent-transformer"
COMMIT = "00155b9a8cb404c0ae38d3809214732aa57a2fdf"
PSP_CHECKPOINT = "external/latent-transformer/pixel2style2pixel/pretrained_models/psp_ffhq_encode.pt"
PSP_SHA256 = "f786ac5cf18fcdbc5c57c9f3f12cbedca69381fbdf5694dd132294e3133749d7"
TNET_DIR = "external/latent-transformer/logs/001"
ORIGINAL_DATASET = "CelebA-HQ"
NATIVE_RESOLUTION = "1024x1024"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an attribute manipulated face"
L3 = "A photo generated by the gan-based model"
L4 = "The source generative model of this photo is LatTrans"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    src_dir = PREPROD_ROOT / "source" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    src_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load pSp
    print("Loading pSp encoder...")
    psp_ckpt = torch.load(PSP_CHECKPOINT, map_location="cpu")
    opts_dict = psp_ckpt["opts"]
    opts_dict["output_size"] = 1024
    opts = argparse.Namespace(**opts_dict)
    opts.checkpoint_path = PSP_CHECKPOINT
    opts.device = device
    net = pSp(opts).eval().to(device)
    print("pSp loaded successfully!")

    # Available real pristine source faces (15 faces)
    real_src_paths = [Path(f"MFVLR_Dataset/images/real/{i:06d}.png") for i in range(15)]
    for p in real_src_paths:
        if not p.exists():
            raise FileNotFoundError(f"Real source face not found: {p}")

    # Pre-encode all 15 faces into latent space W+
    print("Pre-encoding 15 real pristine faces into latent space W+ with pSp...")
    cached_latents = {}
    with torch.no_grad():
        for i, p in enumerate(real_src_paths):
            with Image.open(p) as img:
                img_t = transforms.ToTensor()(img.convert("RGB").resize((256, 256))).unsqueeze(0).to(device)
                img_t = (img_t - 0.5) / 0.5  # [-1, 1]
                codes = net.encoder(img_t)
                if net.opts.start_from_latent_avg:
                    codes = codes + net.latent_avg.repeat(codes.shape[0], 1, 1)
                cached_latents[i] = codes

    # Build 500 deterministic combination pairs: (src_idx, attr_id)
    # 15 source images x 34 attributes = 510 combinations
    combos = []
    for s_idx in range(15):
        for attr_id in range(40):
            tnet_file = Path(TNET_DIR) / f"tnet_{attr_id}.pth.tar"
            if tnet_file.exists():
                combos.append((s_idx, attr_id))
            if len(combos) >= NUM_SAMPLES:
                break
        if len(combos) >= NUM_SAMPLES:
            break

    print(f"Prepared {len(combos)} (source_idx, attribute_id) combinations.")

    # Cache T-Net models as needed
    tnet_models = {}
    def get_tnet(attr_id):
        if attr_id not in tnet_models:
            tnet_path = Path(TNET_DIR) / f"tnet_{attr_id}.pth.tar"
            tnet = F_mapping(mapping_lrmul=1, mapping_layers=18, mapping_fmaps=512, mapping_nonlinearity="linear")
            tnet.load_state_dict(torch.load(tnet_path, map_location="cpu"))
            tnet.eval().to(device)
            tnet_models[attr_id] = (tnet, compute_sha256(tnet_path))
        return tnet_models[attr_id]

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    alpha = torch.tensor([1.5], device=device)

    for idx, (s_idx, attr_id) in enumerate(combos):
        sample_id = f"lattrans_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        src_path = src_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_src_path = str(src_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, src_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(src_path), Image.open(msk_path), Image.open(img_path)])
                continue

        codes = cached_latents[s_idx]
        tnet, tnet_sha = get_tnet(attr_id)

        t0 = time.time()
        with torch.no_grad():
            w_manip = tnet(codes.view(codes.size(0), -1), alpha).view(codes.size())
            # Official LatTrans: [:11] manipulated, [11:] original
            w_final = torch.cat((w_manip[:, :11, :], codes[:, 11:, :]), dim=1)
            fake_tensor, _ = net.decoder([w_final], input_is_latent=True, randomize_noise=False)

            fake_tensor = (fake_tensor.clamp(-1, 1) + 1.0) / 2.0
            fake_np = (fake_tensor[0].permute(1, 2, 0).cpu().numpy() * 255).astype(np.uint8)

        # Source face PIL (224x224)
        src_raw = Image.open(real_src_paths[s_idx]).convert("RGB")
        src_pil = src_raw.resize((224, 224), Image.Resampling.LANCZOS)
        src_pil.save(src_path, format="PNG")

        # Fake face PIL (224x224)
        fake_pil = Image.fromarray(fake_np).resize((224, 224), Image.Resampling.LANCZOS)
        fake_pil.save(img_path, format="PNG")

        # MFVLR strict mask protocol: abs(fake - source) -> ITU-R BT.601 -> /255.0 -> > 0.1 -> {0, 255}
        mask_arr = compute_difference_mask(fake_pil, src_pil, target_size=(224, 224), threshold=0.1)
        save_mask_lossless(mask_arr, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": rel_src_path,
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": f"psp_ffhq_encode.pt + tnet_{attr_id}.pth.tar",
            "checkpoint_sha256": f"psp:{PSP_SHA256[:16]}...;tnet:{tnet_sha[:16]}...",
            "seed": str(idx),
            "source_id": f"{s_idx:06d}.png",
            "target_id": "",
            "generation_config": f"attribute_id={attr_id},alpha=1.5,coarse_layers=11",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": f"Official LatTrans attribute {attr_id} manipulation pre-production sample",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([src_pil, Image.fromarray(mask_arr), fake_pil])

        if (idx + 1) % 50 == 0 or idx == len(combos) - 1:
            print(f"Progress: {idx + 1}/{len(combos)} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "lattrans_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
