import os
import sys
import time
import psutil
import torch
import numpy as np
from PIL import Image
from pathlib import Path
from omegaconf import OmegaConf

# Add project root and latent-diffusion to sys.path
sys.path.insert(0, os.path.abspath("."))
sys.path.insert(0, os.path.abspath("external/latent-diffusion"))

from ldm.util import instantiate_from_config
from ldm.models.diffusion.ddim import DDIMSampler

from scripts.preproduction.common import (
    PREPROD_ROOT,
    METADATA_FIELDS,
    init_workspace,
    get_existing_records,
    is_sample_valid_and_complete,
    append_metadata_record,
    compute_sha256,
    create_contact_sheet,
    save_mask_lossless,
)

GENERATOR = "LatDiff"
FORGERY_TYPE = "EFS"
ARCHITECTURE = "Diffusion"
CATEGORY = "EFS"
REPO = "https://github.com/CompVis/latent-diffusion"
COMMIT = "a506df5756472e2ebaf9078affdde2c4f1502cd4"
CHECKPOINT = "checkpoints/EFS/LatDiff/model.ckpt"
CHECKPOINT_SHA256 = "aa782e2c4f9b49e70be153add726450f4165ed157690fda8258aaaef782b8002"
CONFIG_PATH = "external/latent-diffusion/models/ldm/celeba256/config.yaml"
ORIGINAL_DATASET = "CelebA-HQ"
NATIVE_RESOLUTION = "256x256"
NUM_SAMPLES = 500

L1 = "A photo of a fake face"
L2 = "A photo of an entire synthesized face"
L3 = "A photo generated by the diffusion-based model"
L4 = "The source generative model of this photo is LatDiff"


def main():
    print(f"=== Starting {GENERATOR} Pre-Production Generation ({NUM_SAMPLES} samples) ===")
    init_workspace()

    device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
    print(f"Device: {device}")

    # Verify checkpoint
    ckpt_path = Path(CHECKPOINT)
    if not ckpt_path.exists():
        raise FileNotFoundError(f"Checkpoint not found at {ckpt_path}")
    curr_sha = compute_sha256(ckpt_path)
    if curr_sha != CHECKPOINT_SHA256:
        raise ValueError(f"Checkpoint SHA256 mismatch: {curr_sha} != {CHECKPOINT_SHA256}")
    print(f"Verified checkpoint SHA256: {curr_sha}")

    # Output directories
    img_dir = PREPROD_ROOT / "images" / CATEGORY / GENERATOR
    msk_dir = PREPROD_ROOT / "masks" / CATEGORY / GENERATOR
    img_dir.mkdir(parents=True, exist_ok=True)
    msk_dir.mkdir(parents=True, exist_ok=True)

    csv_path = PREPROD_ROOT / "metadata" / "all_preproduction.csv"
    existing_records = get_existing_records(csv_path)

    # Load official model
    print(f"Loading official {GENERATOR} model from {CONFIG_PATH}...")
    config = OmegaConf.load(CONFIG_PATH)
    config.model.params.ckpt_path = str(ckpt_path)
    model = instantiate_from_config(config.model)
    model.eval().to(device)
    sampler = DDIMSampler(model)
    print("LatDiff model and DDIMSampler ready on CUDA!")

    # Pre-create all-ones mask array (224x224)
    efs_mask = np.full((224, 224), 255, dtype=np.uint8)

    times = []
    contact_samples = []
    generated_count = 0
    skipped_count = 0

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
    process = psutil.Process()

    shape = [3, 64, 64]  # Latent shape for celeba256

    for idx in range(NUM_SAMPLES):
        sample_id = f"latdiff_{idx:06d}"
        img_name = f"{sample_id}.png"
        img_path = img_dir / img_name
        msk_path = msk_dir / img_name

        rel_img_path = str(img_path.relative_to(PREPROD_ROOT)).replace("\\", "/")
        rel_msk_path = str(msk_path.relative_to(PREPROD_ROOT)).replace("\\", "/")

        # Check resumability
        if sample_id in existing_records:
            rec = existing_records[sample_id]
            if is_sample_valid_and_complete(sample_id, rec, [img_path, msk_path]):
                skipped_count += 1
                if len(contact_samples) < 10:
                    contact_samples.append([Image.open(img_path), Image.open(msk_path)])
                continue

        seed = idx
        torch.manual_seed(seed)

        t0 = time.time()
        with torch.no_grad():
            samples, _ = sampler.sample(S=50, batch_size=1, shape=shape, verbose=False, eta=0.0)
            x_samples = model.decode_first_stage(samples)
            x_samples = torch.clamp((x_samples + 1.0) / 2.0, min=0.0, max=1.0)
            img_np = (x_samples[0].permute(1, 2, 0).cpu().numpy() * 255).astype(np.uint8)

        # Resize to strict 224x224 MFVLR protocol
        img_pil = Image.fromarray(img_np).resize((224, 224), Image.Resampling.LANCZOS)
        img_pil.save(img_path, format="PNG")

        # Save EFS mask (all 255)
        save_mask_lossless(efs_mask, msk_path)

        dt = time.time() - t0
        times.append(dt)
        generated_count += 1

        img_sha = compute_sha256(img_path)

        record = {
            "sample_id": sample_id,
            "image_path": rel_img_path,
            "source_path": "",
            "target_path": "",
            "mask_path": rel_msk_path,
            "label": "1",
            "forgery_type": FORGERY_TYPE,
            "architecture": ARCHITECTURE,
            "generator": GENERATOR,
            "split": "UNASSIGNED",
            "L1": L1,
            "L2": L2,
            "L3": L3,
            "L4": L4,
            "original_dataset": ORIGINAL_DATASET,
            "generator_repo": REPO,
            "generator_commit": COMMIT,
            "checkpoint": CHECKPOINT,
            "checkpoint_sha256": CHECKPOINT_SHA256,
            "seed": str(seed),
            "source_id": "",
            "target_id": "",
            "generation_config": "sampler=DDIM,S=50,eta=0.0,latent_shape=[3,64,64]",
            "native_resolution": NATIVE_RESOLUTION,
            "sha256": img_sha,
            "notes": "Official LatDiff synthesis pre-production sample (DDIM 50-step)",
        }
        append_metadata_record(csv_path, record)

        if len(contact_samples) < 10:
            contact_samples.append([img_pil, Image.fromarray(efs_mask)])

        if (idx + 1) % 50 == 0 or idx == NUM_SAMPLES - 1:
            print(f"Progress: {idx + 1}/{NUM_SAMPLES} samples processed (generated: {generated_count}, skipped: {skipped_count})", flush=True)

    peak_vram = torch.cuda.max_memory_allocated() / (1024 ** 2) if torch.cuda.is_available() else 0
    peak_ram = process.memory_info().rss / (1024 ** 2)
    avg_runtime = sum(times) / len(times) if times else 0

    print("\n" + "=" * 60, flush=True)
    print(f"{GENERATOR} COMPLETED:", flush=True)
    print(f"Generated: {generated_count}, Skipped (resumed): {skipped_count}, Total valid: {generated_count + skipped_count}", flush=True)
    print(f"Average runtime/sample: {avg_runtime:.4f}s", flush=True)
    print(f"Peak VRAM: {peak_vram:.2f} MB", flush=True)
    print(f"Peak RAM: {peak_ram:.2f} MB", flush=True)
    print("=" * 60, flush=True)

    # Save visual grid
    grid_path = PREPROD_ROOT / "visual_grids" / "latdiff_preprod_grid.png"
    create_contact_sheet(contact_samples, grid_path)
    print(f"Saved visual grid to {grid_path}", flush=True)


if __name__ == "__main__":
    main()
